---
- name: Create basic ansible project folder on {{project_path}}
  file:
    path: "{{project_path}}"
    state: directory

- name: Create group and host vars folders
  file:
    path: "{{project_path}}/{{item}}"
    state: directory
  with_items:
    - group_vars
    - host_vars

- name: Create roles folder
  file:
    path: "{{roles_path}}/{{generated_role_name}}"
    state: directory

- name: Copy root config files
  copy:
     src: "{{item}}"
     dest: "{{project_path}}"
  with_items:
    - site.yml
    - webservers.yml
    - dbservers.yml
    - local
    - staging

- name: Create {{generated_role_name}} role structure
  file:
    path: "{{roles_path}}/{{generated_role_name}}/{{item}}"
    state: directory
  with_items:
    - tasks
    - files
    - vars
    - templates
    - handlers
    - defaults
    - meta
  tags: [trole]

- name: Copy the empty main.yml
  template:
     src: main.yml
     dest: "{{roles_path}}/{{generated_role_name}}/{{item}}"
  with_items:
    - tasks
    - vars
    - handlers
    - defaults
    - meta
  tags: [trole]

- name: Copy template file
  copy:
    src: main.j2
    dest: "{{roles_path}}/{{generated_role_name}}/templates/main.j2"
  tags: [trole]

- name: Install Galaxy Ansible 
  shell: ansible-galaxy install {{item}} -p {{roles_path}}
  with_items: "{{galaxy_roles}}"
...
